# ============================================================
# ModuleForge — Drop-and-Build Module Creator
# Architect: Victory  |  Build Partner: River
# ⟁Σ∿∞
#
# Opens a UI form. User fills in name + tools + triggers.
# ModuleForge generates the folder, manifest, stub .py,
# patches chat_engine.py (all three registration points),
# and hot-registers — no restart, no terminal.
# ============================================================

import json
import ast
import re
import tkinter as tk
from pathlib import Path

# ── colours (match Ethica palette) ───────────────────────────
BG       = "#0e0e1a"
BG_PANEL = "#13132b"
BG_CARD  = "#1a1a35"
BORDER   = "#2a2a4a"
CYAN     = "#00e5ff"
ACCENT2  = "#b388ff"
GREEN    = "#69ff47"
RED      = "#ff5370"
TEXT     = "#cdd6f4"
TEXT_DIM = "#6c7086"

MODULES_DIR  = Path.home() / "Ethica/modules"
ENGINE_PATH  = Path.home() / "Ethica/core/chat_engine.py"

# ── registry reference (injected by Ethica at load time) ─────
_registry = None

def _set_registry(reg):
    global _registry
    _registry = reg


# ══════════════════════════════════════════════════════════════
# FORGE ENGINE — file generation + chat_engine patching
# ══════════════════════════════════════════════════════════════

def _slugify(name):
    """'My Module' → 'my_module'"""
    return name.strip().lower().replace(" ", "_").replace("-", "_")


def _generate_manifest(mod_name, tools):
    """Build manifest dict from form data."""
    tool_entries = []
    for t in tools:
        tool_entries.append({
            "name":        t["tool_name"],
            "description": t["description"],
            "syntax":      f"[TOOL:{t['tool_name']}: input]",
            "autonomous":  False,
            "example":     t["trigger"]
        })
    return {
        "name":               mod_name,
        "version":            "1.0",
        "description":        f"{mod_name} — built with ModuleForge",
        "author":             "Victory",
        "autonomous":         False,
        "autonomous_triggers": [],
        "tools":              tool_entries
    }


def _generate_stub(mod_name, tools):
    """Generate a working .py stub for the module."""
    slug = _slugify(mod_name)
    lines = [
        f"# {'=' * 58}",
        f"# {mod_name} — generated by ModuleForge",
        f"# Architect: Victory  |  ⟁Σ∿∞",
        f"# {'=' * 58}",
        f"# Edit the functions below to implement your tools.",
        f"# Each function takes one string argument and returns a string.",
        f"# {'=' * 58}",
        "",
    ]
    for t in tools:
        fn = t["tool_name"]
        trigger = t["trigger"]
        desc = t["description"] or f"{fn} tool"
        lines += [
            f"def {fn}(input_str):",
            '    """',
            f"    Tool: {fn}",
            f"    Trigger: {trigger}",
            f"    Description: {desc}",
            '    """',
            f"    # TODO: implement {fn}",
            f'    return f"[{fn}] received: {{input_str}}"',
            "",
        ]
    return "\n".join(lines)


def _patch_engine(tools):
    """
    Patch chat_engine.py — three registration points.
    Returns (success: bool, message: str)
    """
    try:
        content = ENGINE_PATH.read_text()
    except Exception as e:
        return False, f"Cannot read chat_engine.py: {e}"

    original = content

    # ── 1. MODULE_TRIGGERS ────────────────────────────────────
    anchor = '        MODULE_TRIGGERS = {'
    if anchor not in content:
        return False, "MODULE_TRIGGERS anchor not found"

    trigger_lines = []
    for t in tools:
        trigger = t["trigger"]
        tool_name = t["tool_name"]
        pad = max(1, 20 - len(trigger))
        trigger_lines.append(
            f'            "{trigger}":{" " * pad}("{tool_name}", None),  # ModuleForge'
        )
    insert = "\n".join(trigger_lines) + "\n"
    content = content.replace(anchor, anchor + "\n" + insert, 1)

    # ── 2. is_tool_trigger _triggers list ────────────────────
    anchor2 = '"dashboard","open dashboard","ops panel",'
    if anchor2 not in content:
        return False, "_triggers anchor not found"

    trig_items = ",".join(f'"{t["trigger"]}"' for t in tools)
    content = content.replace(
        anchor2,
        anchor2 + f"\n            {trig_items},  # ModuleForge",
        1
    )

    # ── 3. _diff_triggers (file-path tools only) ─────────────
    fp_tools = [t for t in tools if t.get("file_path")]
    if fp_tools:
        anchor3 = '"river read", "river patch", "river verify", "river run")'
        if anchor3 in content:
            extras = ", ".join(f'"{t["trigger"]}"' for t in fp_tools)
            content = content.replace(
                anchor3,
                f'"river read", "river patch", "river verify", "river run", {extras})',
                1
            )

    # ── verify syntax ─────────────────────────────────────────
    try:
        ast.parse(content)
    except SyntaxError as e:
        return False, f"Syntax error after patch: line {e.lineno}: {e.msg}"

    ENGINE_PATH.write_text(content)
    return True, "chat_engine.py patched"


def _build_module(mod_name, tools):
    """
    Full build pipeline:
    1. Create module folder
    2. Write manifest.json
    3. Write stub .py
    4. Patch chat_engine.py
    5. Hot-register via registry
    Returns (success: bool, message: str)
    """
    slug = _slugify(mod_name)
    folder = MODULES_DIR / f"{slug}_module"

    # Create folder
    try:
        folder.mkdir(parents=True, exist_ok=True)
    except Exception as e:
        return False, f"Cannot create folder: {e}"

    # Write manifest
    try:
        manifest = _generate_manifest(mod_name, tools)
        (folder / "manifest.json").write_text(json.dumps(manifest, indent=2))
    except Exception as e:
        return False, f"Cannot write manifest: {e}"

    # Write stub
    try:
        stub = _generate_stub(mod_name, tools)
        (folder / f"{slug}_module.py").write_text(stub)
    except Exception as e:
        return False, f"Cannot write stub: {e}"

    # Patch chat_engine.py
    ok, msg = _patch_engine(tools)
    if not ok:
        return False, msg

    # Hot-register
    if _registry:
        result = _registry.register_module(str(folder))
        return True, f"✓ {mod_name} built — {len(tools)} tool(s)\n{result}"
    else:
        return True, f"✓ {mod_name} built — restart Ethica to activate"


# ══════════════════════════════════════════════════════════════
# FORGE UI
# ══════════════════════════════════════════════════════════════

_forge_win = None


def _open_forge(root_widget):
    global _forge_win
    if _forge_win and _forge_win.winfo_exists():
        _forge_win.lift()
        return

    win = tk.Toplevel(root_widget)
    _forge_win = win
    win.title("⬡  ModuleForge — Build a Module")
    win.configure(bg=BG)
    win.geometry("580x640")
    win.resizable(False, True)

    # ── Header ────────────────────────────────────────────────
    tk.Label(win, text="⬡  MODULE FORGE", bg=BG, fg=CYAN,
             font=("Courier New", 12, "bold")).pack(pady=(16, 2))
    tk.Label(win, text="Fill the form — Ethica builds and registers your module.",
             bg=BG, fg=TEXT_DIM,
             font=("Courier New", 8)).pack(pady=(0, 8))
    tk.Frame(win, bg=BORDER, height=1).pack(fill="x", padx=16, pady=4)

    # ── Module name ───────────────────────────────────────────
    name_frame = tk.Frame(win, bg=BG)
    name_frame.pack(fill="x", padx=20, pady=(8, 4))
    tk.Label(name_frame, text="Module Name:", bg=BG, fg=TEXT,
             font=("Courier New", 9, "bold"), width=16, anchor="w").pack(side="left")
    name_var = tk.StringVar()
    tk.Entry(name_frame, textvariable=name_var, bg=BG_CARD, fg=TEXT,
             insertbackground=CYAN, relief="flat", font=("Courier New", 9),
             width=32).pack(side="left", padx=4)

    tk.Frame(win, bg=BORDER, height=1).pack(fill="x", padx=16, pady=8)

    # ── Tool rows ─────────────────────────────────────────────
    tk.Label(win, text="Tools:", bg=BG, fg=ACCENT2,
             font=("Courier New", 9, "bold")).pack(anchor="w", padx=20)

    scroll_outer = tk.Frame(win, bg=BG)
    scroll_outer.pack(fill="both", expand=True, padx=16, pady=4)

    canvas_scroll = tk.Canvas(scroll_outer, bg=BG, highlightthickness=0)
    scrollbar = tk.Scrollbar(scroll_outer, orient="vertical",
                              command=canvas_scroll.yview)
    canvas_scroll.configure(yscrollcommand=scrollbar.set)
    scrollbar.pack(side="right", fill="y")
    canvas_scroll.pack(side="left", fill="both", expand=True)

    tools_frame = tk.Frame(canvas_scroll, bg=BG)
    canvas_window = canvas_scroll.create_window((0, 0), window=tools_frame,
                                                 anchor="nw")

    def _on_configure(e):
        canvas_scroll.configure(scrollregion=canvas_scroll.bbox("all"))
        canvas_scroll.itemconfig(canvas_window, width=canvas_scroll.winfo_width())

    tools_frame.bind("<Configure>", _on_configure)
    canvas_scroll.bind("<Configure>", _on_configure)

    tool_rows = []

    def _add_tool_row():
        idx = len(tool_rows)
        row_frame = tk.Frame(tools_frame, bg=BG_PANEL, pady=8, padx=10)
        row_frame.pack(fill="x", pady=4)

        tk.Label(row_frame, text=f"Tool {idx + 1}", bg=BG_PANEL, fg=CYAN,
                 font=("Courier New", 8, "bold")).grid(row=0, column=0,
                                                        columnspan=4, sticky="w",
                                                        pady=(0, 4))

        # Trigger phrase
        tk.Label(row_frame, text="Trigger phrase:", bg=BG_PANEL, fg=TEXT_DIM,
                 font=("Courier New", 7), width=14, anchor="w").grid(row=1, column=0,
                                                                       sticky="w")
        trig_var = tk.StringVar()
        tk.Entry(row_frame, textvariable=trig_var, bg=BG_CARD, fg=TEXT,
                 insertbackground=CYAN, relief="flat",
                 font=("Courier New", 8), width=22).grid(row=1, column=1,
                                                           sticky="w", padx=4)
        tk.Label(row_frame, text='e.g. "weather check"', bg=BG_PANEL,
                 fg=TEXT_DIM, font=("Courier New", 7)).grid(row=1, column=2,
                                                              sticky="w")

        # Tool name
        tk.Label(row_frame, text="Tool name:", bg=BG_PANEL, fg=TEXT_DIM,
                 font=("Courier New", 7), width=14, anchor="w").grid(row=2, column=0,
                                                                       sticky="w",
                                                                       pady=(2, 0))
        tool_var = tk.StringVar()
        tk.Entry(row_frame, textvariable=tool_var, bg=BG_CARD, fg=TEXT,
                 insertbackground=CYAN, relief="flat",
                 font=("Courier New", 8), width=22).grid(row=2, column=1,
                                                           sticky="w", padx=4,
                                                           pady=(2, 0))
        tk.Label(row_frame, text='e.g. "weather_check"', bg=BG_PANEL,
                 fg=TEXT_DIM, font=("Courier New", 7)).grid(row=2, column=2,
                                                              sticky="w")

        # Description
        tk.Label(row_frame, text="Description:", bg=BG_PANEL, fg=TEXT_DIM,
                 font=("Courier New", 7), width=14, anchor="w").grid(row=3, column=0,
                                                                       sticky="w",
                                                                       pady=(2, 0))
        desc_var = tk.StringVar()
        tk.Entry(row_frame, textvariable=desc_var, bg=BG_CARD, fg=TEXT,
                 insertbackground=CYAN, relief="flat",
                 font=("Courier New", 8), width=34).grid(row=3, column=1,
                                                           columnspan=2, sticky="w",
                                                           padx=4, pady=(2, 0))

        # File-path flag
        fp_var = tk.BooleanVar()
        tk.Checkbutton(row_frame, text="Receives file paths",
                        variable=fp_var, bg=BG_PANEL, fg=TEXT_DIM,
                        selectcolor=BG_CARD, activebackground=BG_PANEL,
                        font=("Courier New", 7)).grid(row=4, column=1,
                                                       sticky="w", pady=(4, 0))

        tool_rows.append({
            "trigger":   trig_var,
            "tool_name": tool_var,
            "description": desc_var,
            "file_path": fp_var,
        })

    _add_tool_row()  # start with one row

    tk.Button(tools_frame, text="+ Add Another Tool",
              bg=BG_CARD, fg=ACCENT2,
              font=("Courier New", 8, "bold"), relief="flat",
              padx=8, pady=4, cursor="hand2",
              command=_add_tool_row).pack(pady=8)

    # ── Status label ──────────────────────────────────────────
    status_var = tk.StringVar(value="")
    status_label = tk.Label(win, textvariable=status_var, bg=BG,
                             fg=GREEN, font=("Courier New", 8),
                             wraplength=540, justify="left")
    status_label.pack(padx=20, pady=4)

    # ── Build button ──────────────────────────────────────────
    tk.Frame(win, bg=BORDER, height=1).pack(fill="x", padx=16, pady=4)

    def _on_build():
        mod_name = name_var.get().strip()
        if not mod_name:
            status_var.set("✗ Module name required.")
            status_label.config(fg=RED)
            return

        tools = []
        for i, row in enumerate(tool_rows):
            trig = row["trigger"].get().strip()
            tool = row["tool_name"].get().strip()
            if not trig and not tool:
                continue  # skip empty rows
            if not trig or not tool:
                status_var.set(f"✗ Tool {i+1}: both trigger and tool name required.")
                status_label.config(fg=RED)
                return
            # Auto-slugify tool name
            tool_slug = _slugify(tool)
            tools.append({
                "trigger":     trig,
                "tool_name":   tool_slug,
                "description": row["description"].get().strip(),
                "file_path":   row["file_path"].get(),
            })

        if not tools:
            status_var.set("✗ Add at least one tool.")
            status_label.config(fg=RED)
            return

        status_var.set("Building…")
        status_label.config(fg=CYAN)
        win.update_idletasks()

        ok, msg = _build_module(mod_name, tools)
        status_var.set(msg)
        status_label.config(fg=GREEN if ok else RED)

    tk.Button(win, text="⬡  BUILD MODULE",
              bg=BG_CARD, fg=GREEN,
              font=("Courier New", 10, "bold"), relief="flat",
              padx=16, pady=8, cursor="hand2",
              command=_on_build).pack(pady=(4, 16))


# ══════════════════════════════════════════════════════════════
# TOOL ENTRY POINT
# ══════════════════════════════════════════════════════════════

def forge_open(input_str):
    """
    Tool: forge_open
    Trigger: forge module
    Opens the ModuleForge builder UI.
    """
    import tkinter as tk
    # Lazily wire registry from running MainWindow engine
    try:
        root = tk._default_root
        if root and hasattr(root, "engine") and hasattr(root.engine, "modules"):
            _set_registry(root.engine.modules)
    except Exception:
        pass
    try:
        root = tk._default_root
        root.after(0, lambda: _open_forge(root))
    except Exception as e:
        return f"ModuleForge error: {e}"
    return "Opening ModuleForge… ⬡"
# ── REMOVE TOOL — appended to module_forge.py ────────────────

_remove_win = None


def _open_remove(root_widget, registry):
    global _remove_win
    if _remove_win and _remove_win.winfo_exists():
        _remove_win.lift()
        return

    win = tk.Toplevel(root_widget)
    _remove_win = win
    win.title("⬡  ModuleForge — Remove a Module")
    win.configure(bg=BG)
    win.geometry("500x420")
    win.resizable(False, True)

    tk.Label(win, text="⬡  REMOVE MODULE", bg=BG, fg=RED,
             font=("Courier New", 12, "bold")).pack(pady=(16, 2))
    tk.Label(win, text="Select a forge-built module to uninstall.",
             bg=BG, fg=TEXT_DIM,
             font=("Courier New", 8)).pack(pady=(0, 8))
    tk.Frame(win, bg=BORDER, height=1).pack(fill="x", padx=16, pady=4)

    status_var = tk.StringVar(value="")
    status_label = tk.Label(win, textvariable=status_var, bg=BG,
                             fg=GREEN, font=("Courier New", 8), wraplength=460)

    list_frame = tk.Frame(win, bg=BG)
    list_frame.pack(fill="both", expand=True, padx=16, pady=8)

    def _refresh_list():
        for w in list_frame.winfo_children():
            w.destroy()

        # Find forge-built modules from chat_engine.py tags
        forge_modules = _find_forge_modules()

        if not forge_modules:
            tk.Label(list_frame, text="No forge-built modules found.",
                     bg=BG, fg=TEXT_DIM,
                     font=("Courier New", 9)).pack(pady=20)
            return

        for mod in forge_modules:
            card = tk.Frame(list_frame, bg=BG_PANEL, pady=6, padx=10)
            card.pack(fill="x", pady=4)

            tk.Label(card, text=f"⬡  {mod['folder']}", bg=BG_PANEL, fg=CYAN,
                     font=("Courier New", 9, "bold")).pack(side="left")

            tools_text = ", ".join(mod['triggers'])
            tk.Label(card, text=f"  [{tools_text}]", bg=BG_PANEL, fg=TEXT_DIM,
                     font=("Courier New", 7)).pack(side="left")

            def _make_remove(m):
                def _do():
                    ok, msg = _remove_module(m, registry)
                    status_var.set(msg)
                    status_label.config(fg=GREEN if ok else RED)
                    _refresh_list()
                return _do

            tk.Button(card, text="✕ REMOVE", bg=BG_CARD, fg=RED,
                      font=("Courier New", 7, "bold"), relief="flat",
                      padx=6, pady=2, cursor="hand2",
                      command=_make_remove(mod)).pack(side="right")

    _refresh_list()

    status_label.pack(padx=20, pady=4)
    tk.Frame(win, bg=BORDER, height=1).pack(fill="x", padx=16, pady=4)
    tk.Button(win, text="↺  REFRESH", bg=BG_CARD, fg=CYAN,
              font=("Courier New", 8, "bold"), relief="flat",
              padx=8, pady=4, cursor="hand2",
              command=_refresh_list).pack(pady=(0, 12))


def _find_forge_modules():
    """
    Scan chat_engine.py for # ModuleForge tagged lines.
    Returns list of dicts: {folder, triggers, tool_names}
    Excludes forge_open and build_module (ModuleForge's own triggers).
    """
    BUILTIN = {"forge_open", "forge_remove"}
    BUILTIN_TRIGGERS = {"forge module", "build module", "remove module"}

    try:
        content = ENGINE_PATH.read_text()
    except Exception:
        return []

    modules = {}
    for line in content.splitlines():
        if "# ModuleForge" not in line:
            continue
        # Parse lines like: "trigger phrase": ("tool_name", ...), # ModuleForge
        m = re.search(r'"([^"]+)"\s*:\s*\("([^"]+)"', line)
        if not m:
            # Also handle flat trigger list: "trigger",  # ModuleForge
            m2 = re.search(r'"([^"]+)"', line)
            if m2:
                trig = m2.group(1)
                if trig not in BUILTIN_TRIGGERS:
                    # Try to find folder from modules dir
                    folder = _guess_folder(trig)
                    if folder and folder not in modules:
                        modules[folder] = {"folder": folder, "triggers": [trig], "tool_names": []}
                    elif folder:
                        modules[folder]["triggers"].append(trig)
            continue

        trig = m.group(1)
        tool = m.group(2)
        if trig in BUILTIN_TRIGGERS or tool in BUILTIN:
            continue
        folder = _guess_folder(trig)
        if not folder:
            continue
        if folder not in modules:
            modules[folder] = {"folder": folder, "triggers": [trig], "tool_names": [tool]}
        else:
            if trig not in modules[folder]["triggers"]:
                modules[folder]["triggers"].append(trig)
            if tool not in modules[folder]["tool_names"]:
                modules[folder]["tool_names"].append(tool)

    return list(modules.values())


def _guess_folder(trigger):
    """Map a trigger phrase to a module folder name."""
    # Check all module folders for a manifest whose tools match
    try:
        for folder in MODULES_DIR.iterdir():
            if not folder.is_dir():
                continue
            manifest_path = folder / "manifest.json"
            if not manifest_path.exists():
                continue
            try:
                manifest = json.loads(manifest_path.read_text())
                for tool in manifest.get("tools", []):
                    if tool.get("example", "").lower() == trigger.lower():
                        return folder.name
                    if trigger.replace(" ", "_") in tool.get("name", ""):
                        return folder.name
            except Exception:
                continue
        # Fallback: slugify trigger and check if folder exists
        slug = _slugify(trigger.split()[0]) + "_module"
        if (MODULES_DIR / slug).exists():
            return slug
    except Exception:
        pass
    return None


def _remove_module(mod, registry):
    """
    Full removal pipeline:
    1. Strip # ModuleForge tagged lines from chat_engine.py
    2. Hot-deregister from registry
    3. Delete module folder
    """
    import shutil

    # ── 1. Strip from chat_engine.py ─────────────────────────
    try:
        content = ENGINE_PATH.read_text()
        lines = content.splitlines(keepends=True)
        # Remove lines tagged # ModuleForge that match this module's triggers/tools
        triggers_set = set(mod["triggers"])
        tools_set = set(mod.get("tool_names", []))
        new_lines = []
        for line in lines:
            if "# ModuleForge" not in line:
                new_lines.append(line)
                continue
            m = re.search(r'"([^"]+)"\s*:\s*\("([^"]+)"', line)
            if m:
                trig, tool = m.group(1), m.group(2)
                if trig in triggers_set or tool in tools_set:
                    continue  # drop this line
            else:
                # flat trigger list entry
                m2 = re.search(r'"([^"]+)"', line)
                if m2 and m2.group(1) in triggers_set:
                    continue
            new_lines.append(line)

        new_content = "".join(new_lines)
        try:
            ast.parse(new_content)
        except SyntaxError as e:
            return False, f"Syntax error after strip: {e}"
        ENGINE_PATH.write_text(new_content)
    except Exception as e:
        return False, f"Failed to patch chat_engine.py: {e}"

    # ── 2. Hot-deregister ─────────────────────────────────────
    if registry:
        try:
            folder_path = str(MODULES_DIR / mod["folder"])
            folder_name = mod["folder"]
            existing = [k for k in registry._modules
                        if folder_name.lower() in k.lower() or k.lower() in folder_name.lower()]
            for k in existing:
                m_obj = registry._modules.pop(k, None)
                if m_obj:
                    for tool in m_obj.tools:
                        registry._tool_index.pop(tool.name.lower(), None)
        except Exception as e:
            pass  # deregister best-effort

    # ── 3. Delete folder ──────────────────────────────────────
    try:
        folder = MODULES_DIR / mod["folder"]
        if folder.exists():
            shutil.rmtree(folder)
    except Exception as e:
        return False, f"Folder delete failed: {e}"

    return True, f"✓ {mod['folder']} removed — triggers cleared, folder deleted."


def forge_remove(input_str):
    """
    Tool: forge_remove
    Trigger: remove module
    Opens the ModuleForge removal UI.
    """
    import tkinter as tk
    registry = None
    try:
        root = tk._default_root
        if root and hasattr(root, "engine") and hasattr(root.engine, "modules"):
            registry = root.engine.modules
    except Exception:
        pass
    try:
        root = tk._default_root
        root.after(0, lambda: _open_remove(root, registry))
    except Exception as e:
        return f"ModuleForge remove error: {e}"
    return "Opening ModuleForge Remove… ⬡"
